API_TOKEN: c93598e3-1571-46cb-8f96-02d2ca8d1280
GIT_SSH_URI: git@github.com:manulife-ets/mith_calculator.git
GIT_PRIVATE_KEY: |
 -----BEGIN OPENSSH PRIVATE KEY-----
 b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
 QyNTUxOQAAACABQTFA68sN62SOzCzYSsu9glg1w/Y3lDvKywkuzzVbCAAAAKi7jDZ9u4w2
 fQAAAAtzc2gtZWQyNTUxOQAAACABQTFA68sN62SOzCzYSsu9glg1w/Y3lDvKywkuzzVbCA
 AAAEBCGTHMPgZjED1EKnE4gDjSdYh3Tu/zTNggM2FITERmOAFBMUDryw3rZI7MLNhKy72C
 WDXD9jeUO8rLCS7PNVsIAAAAH21pdGhpbGFuX3NpdmFuZXNhbkBtYW51bGlmZS5jb20BAg
 MEBQY=
 -----END OPENSSH PRIVATE KEY-----