---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: gees-docker.artifactory.platform.manulife.io:443/buildtools-node

inputs:
- name: source

run:
  path: source/concourse/scripts/push-dev.sh